### PR TITLE
Update setup.py to reflect Python 3 support

### PR DESCRIPTION
**Pull request by r-darwish**
Orochi seems to work as expected in Python 3.5 thanks to fd85485da4779618bdadc2f1171b1b5fb551be34. Could you please upload a new version to PyPi?

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! You tested both 3.4 and 3.5, right? (Although I don't assume there will be problems with 3.4 if it runs on 3.5...)

**Comment by r-darwish** [comment]
I also assumed that there'll be no problems with 3.4 so I didn't check it. I can check if you want

**Comment by dbrgn** [comment]
Thanks, I also tested 3.3 without any problems.

**Comment by dbrgn** [comment]
I merged your commit into #63. Thanks! Will release soon.

**Comment by dbrgn** [comment]
Version 1.3 is released.

In case you're an ArchLinux user, there's now also an AUR package.

**Comment by r-darwish** [comment]
Awesome :+1: 
@spatz

**Pull request closed without merging**
