### PR TITLE
Add terminal title option; enable readline history

### PR DESCRIPTION
**Pull request by bshillingford**
* Use ANSI control codes to output current song/artist to terminal title. Off by default, stores in settings like all other settings. Updates each time status is updated.
* Enable readline history for persistently scrolling through history. History file stored in same dir as config, silently fails if it can't load/save it, since it's a nonessential feature.

Cheers,
Brendan

### CODE REVIEW

**Comment by dbrgn** [comment]
Hey. I'm very sorry for not answering sooner, I somehow missed the notification email.

This is a great feature, I had no idea you could set the terminal title using ANSI escape codes.

But why is this a optional feature? Why not enable it by default?

**Comment by bshillingford** [comment]
I assumed not all terminals support this feature, although I guess that's
true for colour too. I'll change it to on by default later.

A better solution would be to check termcap/terminfo for colour/title
support, but I'm not sure how to do this and don't want to add non-builtin
dependencies.

**Comment by dbrgn** [comment]
Right now I'd simply assume ANSI compatibility.

I tested it in xterm as well as in the OS X terminal, they both supported the escape sequences. They don't work in IDLE, but on the other hand the colors don't work in there either.

**Comment by dbrgn** [comment]
Sorry again for not answering sooner, but I don't get any notification for new commit pushes without comments :)

Strictly speaking the readline history shouldn't belong in the XDG_CONFIG_HOME directory, but instead in the XDG_CACHE_HOME directory. But I can do that change myself.

**Comment by dbrgn** [comment]
Merged in 929fd23 and 521afb0.

**Pull request closed without merging**
